table fact_game_results
	lineageTag: 8527bc12-86f8-4b5b-a6f9-b770cbc12c38

	measure Games = COUNTROWS(fact_game_results)
		lineageTag: ab417d50-bc94-47c0-a7ca-9a88cd396fdb

	measure Wins = SUM(fact_game_results[Win])
		lineageTag: 0bfa6ffe-356d-4a99-8904-80713721d0e9

	measure Losses = [Games] - [Wins]
		lineageTag: 08b085ca-8eb4-4056-b4bc-d4ef22d5a558

	measure Win% = DIVIDE([Wins], [Games], 0) * 100
		lineageTag: e60b47ad-d2f9-42f0-affc-8267837bb42b

	measure 'Avg Points Scored' = AVERAGE(fact_game_results[Points Scored])
		lineageTag: 27ba0e3e-d8bc-4b41-99bc-916bd98e6415

	measure 'Avg Points Allowed' = AVERAGE(fact_game_results[Points Allowed])
		lineageTag: 46cd263b-29d5-4a1e-bdb2-15b35606c2ea

	measure 'Avg Point Diff' = AVERAGE(fact_game_results[Point Diff])
		lineageTag: cd94440d-7b5d-4f5c-990c-30f19758c346

	measure 'Home Win%' =
			VAR HomeGames =
				CALCULATE(COUNTROWS(fact_game_results), fact_game_results[Location] = "Home")
			VAR HomeWins =
				CALCULATE(SUM(fact_game_results[Win]), fact_game_results[Location] = "Home")
			RETURN
				DIVIDE(HomeWins, HomeGames, 0) * 100
		lineageTag: 63220c58-2750-459e-ac22-65d7deda5965

	measure 'Away Win%' =
			VAR AwayGames =
				CALCULATE(COUNTROWS(fact_game_results), fact_game_results[Location] = "Away")
			VAR AwayWins =
				CALCULATE(SUM(fact_game_results[Win]), fact_game_results[Location] = "Away")
			RETURN
				DIVIDE(AwayWins, AwayGames, 0) * 100
		lineageTag: 7fb6f4e2-d177-458f-a533-86ace199293b

	measure 'Home Advantage' = [Home Win%] - [Away Win%]
		lineageTag: 1c145ccd-d030-45bc-baa2-19aa25e49dc3

	measure 'Avg Home Point Diff' = CALCULATE(AVERAGE(fact_game_results[Point Diff]), fact_game_results[Location] = "Home")
		lineageTag: 8f40bdfb-bc0a-4648-8640-807d868d38f0

	measure 'Avg Away Point Diff' = CALCULATE(AVERAGE(fact_game_results[Point Diff]), fact_game_results[Location] = "Away")
		lineageTag: f484e983-a8e1-4241-a93e-f78736dcbde6

	measure 'Home Games' = CALCULATE(COUNTROWS(fact_game_results), fact_game_results[Location] = "Home")
		lineageTag: 9baf5956-5757-4705-a58f-490c6c630f5a

	measure 'Away Games' = CALCULATE(COUNTROWS(fact_game_results), fact_game_results[Location] = "Away")
		lineageTag: dec9315b-3f2a-4595-a962-e03973a191f9

	measure 'Home Wins' = CALCULATE(SUM(fact_game_results[Win]), fact_game_results[Location] = "Home")
		lineageTag: 38d8a6a8-83c5-4b53-9fd6-aea313999866

	measure 'Away Wins' = CALCULATE(SUM(fact_game_results[Win]), fact_game_results[Location] = "Away")
		lineageTag: a1375915-fdd9-4f50-be6d-a30730a64196

	measure 'Net Point Diff' = AVERAGE(fact_game_results[Point Diff])
		lineageTag: b1c2d3e4-f5a6-7890-abcd-ef1234567890

	measure 'Close Games' = CALCULATE(COUNTROWS(fact_game_results), ABS(fact_game_results[Point Diff]) <= 5)
		lineageTag: c2d3e4f5-a6b7-8901-bcde-f12345678901

	measure 'Close Game Win%' = DIVIDE(CALCULATE(SUM(fact_game_results[Win]), ABS(fact_game_results[Point Diff]) <= 5), [Close Games], 0) * 100
		lineageTag: d3e4f5a6-b7c8-9012-cdef-012345678902

	column game_id
		dataType: int64
		formatString: 0
		lineageTag: 40ff7262-4e66-4c3f-b609-840f926c8a7f
		summarizeBy: none
		sourceColumn: game_id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: bbe93422-3a4c-42d5-864d-3dc4c085eab1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column team_id
		dataType: string
		lineageTag: a06d2bcd-282d-4224-a254-2000d9bd0757
		summarizeBy: none
		sourceColumn: team_id

		annotation SummarizationSetBy = Automatic

	column 'Team Name'
		dataType: string
		lineageTag: 1c5e2bc3-68c4-4d47-b147-6ed0abb39150
		summarizeBy: none
		sourceColumn: Team Name

		annotation SummarizationSetBy = Automatic

	column 'Points Scored'
		dataType: int64
		formatString: 0
		lineageTag: 5e529b57-295e-4c83-8530-fc2f3957f1d0
		summarizeBy: sum
		sourceColumn: Points Scored

		annotation SummarizationSetBy = Automatic

	column 'Points Allowed'
		dataType: int64
		formatString: 0
		lineageTag: fc787f1a-5c1c-4998-bb66-e7e1aabc2db6
		summarizeBy: sum
		sourceColumn: Points Allowed

		annotation SummarizationSetBy = Automatic

	column Win
		dataType: int64
		formatString: 0
		lineageTag: 91c1898b-a18f-43c1-b5d9-21c6f0571c31
		summarizeBy: sum
		sourceColumn: Win

		annotation SummarizationSetBy = Automatic

	column 'Point Diff'
		dataType: int64
		formatString: 0
		lineageTag: c1800c3e-33ef-492c-8c11-43eb5ce17902
		summarizeBy: sum
		sourceColumn: Point Diff

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: d1a2b3c4-1234-5678-abcd-111122223333
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: e2b3c4d5-2345-6789-bcde-222233334444
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: f3c4d5e6-3456-789a-cdef-333344445555
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition fact_game_results = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Johnsinvi/nba-analytics-dashboard/main/data/raw/game_log.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders,{
				        {"game_id", Int64.Type},
				        {"Date", type date},
				        {"Home Team", type text},
				        {"Home Team Name", type text},
				        {"Home Score", Int64.Type},
				        {"Away Team", type text},
				        {"Away Team Name", type text},
				        {"Away Score", Int64.Type}
				    }),
				    RemoveExhibition = Table.SelectRows(ChangeTypes, each not Text.StartsWith(Text.From([game_id]), "325")),
				    StandardizeAbbr = Table.TransformColumns(RemoveExhibition, {
				        {"Home Team", each let t = _ in
				            if t = "GSW" then "GS"
				            else if t = "NYK" then "NY"
				            else if t = "NOP" then "NO"
				            else if t = "UTA" then "UTAH"
				            else if t = "WAS" then "WSH"
				            else if t = "SAS" then "SA"
				            else t},
				        {"Away Team", each let t = _ in
				            if t = "GSW" then "GS"
				            else if t = "NYK" then "NY"
				            else if t = "NOP" then "NO"
				            else if t = "UTA" then "UTAH"
				            else if t = "WAS" then "WSH"
				            else if t = "SAS" then "SA"
				            else t}
				    }),
				    NbaTeams = {"ATL","BKN","BOS","CHA","CHI","CLE","DAL","DEN","DET","GS","HOU","IND","LAC","LAL","MEM","MIA","MIL","MIN","NO","NY","OKC","ORL","PHI","PHX","POR","SA","SAC","TOR","UTAH","WSH"},
				    RemoveNonNba = Table.SelectRows(StandardizeAbbr, each List.Contains(NbaTeams, [Home Team]) and List.Contains(NbaTeams, [Away Team])),
				    HomeRows = Table.AddColumn(RemoveNonNba, "_Location", each "Home"),
				    HomeSelect = Table.SelectColumns(HomeRows, {"game_id","Date","Home Team","Home Team Name","Home Score","Away Score","_Location"}),
				    HomeRenamed = Table.RenameColumns(HomeSelect, {
				        {"Home Team", "team_id"},
				        {"Home Team Name", "Team Name"},
				        {"Home Score", "Points Scored"},
				        {"Away Score", "Points Allowed"},
				        {"_Location", "Location"}
				    }),
				    HomeWithWin = Table.AddColumn(HomeRenamed, "Win", each if [Points Scored] > [Points Allowed] then 1 else 0, Int64.Type),
				    HomeWithDiff = Table.AddColumn(HomeWithWin, "Point Diff", each [Points Scored] - [Points Allowed], Int64.Type),
				    AwayRows = Table.AddColumn(RemoveNonNba, "_Location", each "Away"),
				    AwaySelect = Table.SelectColumns(AwayRows, {"game_id","Date","Away Team","Away Team Name","Away Score","Home Score","_Location"}),
				    AwayRenamed = Table.RenameColumns(AwaySelect, {
				        {"Away Team", "team_id"},
				        {"Away Team Name", "Team Name"},
				        {"Away Score", "Points Scored"},
				        {"Home Score", "Points Allowed"},
				        {"_Location", "Location"}
				    }),
				    AwayWithWin = Table.AddColumn(AwayRenamed, "Win", each if [Points Scored] > [Points Allowed] then 1 else 0, Int64.Type),
				    AwayWithDiff = Table.AddColumn(AwayWithWin, "Point Diff", each [Points Scored] - [Points Allowed], Int64.Type),
				    Combined = Table.Combine({HomeWithDiff, AwayWithDiff}),
				    AddSeason = Table.AddColumn(Combined, "Season", each
				        let yr = Date.Year([Date]), mo = Date.Month([Date])
				        in if mo >= 10 then Text.From(yr) & "-" & Text.End(Text.From(yr + 1), 2)
				           else Text.From(yr - 1) & "-" & Text.End(Text.From(yr), 2),
				        type text),
				    AddMonth = Table.AddColumn(AddSeason, "Month", each
				        Text.From(Date.Year([Date])) & "-" & Text.PadStart(Text.From(Date.Month([Date])), 2, "0"),
				        type text),
				    FinalTypes = Table.TransformColumnTypes(AddMonth, {{"Date", type date}, {"game_id", Int64.Type}})
				in
				    FinalTypes

	annotation PBI_ResultType = Table

